### ISSUE TITLE
Consider embedding with rust-openssl

### ISSUE THREAD

**Issue by vhbit** [alexcrichton/openssl-sys#1]
@alexcrichton Any objections on embedding it into `rust-openssl`?
https://github.com/sfackler/rust-openssl/pull/95

**Comment by alexcrichton** [comment]
I'd actually love to do so! I'm also willing to relicense this under whatever @sfackler's preferred license is for rust-openssl to make things easier.

ping @sfackler, would you like me to make a PR for this?

**Comment by vhbit** [comment]
@alexcrichton there is a PR already (see link in the first comment), even with current MIT license included :)

**Comment by alexcrichton** [comment]
Oh awesome, thanks @vhbit! I'll add a deprecation notice to this repo once that's merged.
